version: '3'

services:
  bookie:
    container_name: bookie-dev
    build: .
    command: bash -c "python manage.py makemigrations --settings=bookie.env.dev && python manage.py migrate --settings=bookie.env.dev && python manage.py runserver 0.0.0.0:8000 --settings=bookie.env.dev"
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ".:/home/bookie/project/"
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
    depends_on:
      - postgres
      - redis

  celery-worker:
    build: .
    command: python -m celery worker -A bookie --concurrency=10 --loglevel=DEBUG
    environment:
      - POSTGRES_USER=bookie
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=bookie
    depends_on:
      - redis
      - postgres
    volumes:
      - ".:/home/bookie/project/"

  celery-beat:
    build: .
    command: python -m celery beat -A bookie --pidfile= --loglevel=DEBUG -S django
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER=bookie
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=bookie
    volumes:
      - ".:/home/bookie/project/"

  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=bookie
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=bookie
    ports:
      - "0.0.0.0:5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@dubell.io
      - PGADMIN_DEFAULT_PASSWORD=asdf
      - PGADMIN_LISTEN_PORT=8484
    ports:
      - "0.0.0.0:8484:8484"

  redis:
    image: redis:5.0.3-alpine
