version: '3'

services:
  bookie:
    container_name: bookie-prod
    image: dubs3c/bookie:latest
    command: sh entrypoint.sh prod
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./static:/home/bookie/project/static"
    env_file:
      - /root/bookie.env
      - /root/bookie.db.env
    depends_on:
      - postgres
      - redis

  celery-worker:
    image: dubs3c/bookie:latest
    command: python -m celery -A bookie worker --concurrency=10 --loglevel=INFO
    env_file:
      - /root/bookie.env
      - /root/bookie.db.env
    depends_on:
      - redis
      - postgres

  celery-beat:
    image: dubs3c/bookie:latest
    command: python -m celery -A bookie beat -S django --loglevel=INFO
    depends_on:
      - postgres
      - redis
    env_file:
      - /root/bookie.env
      - /root/bookie.db.env

  postgres:
    image: postgres:11.6-alpine
    env_file:
      - /root/bookie.db.env
    volumes:
      - /var/lib/bookie/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine