# Generated by Django 2.1.5 on 2019-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='link',
            field=models.TextField(),
        ),
    ]
