# Generated by Django 2.1.5 on 2019-02-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarks",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="bookmarks",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
