# Generated by Django 2.1.5 on 2019-02-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_bookmarks_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegram",
            name="user",
        ),
        migrations.DeleteModel(
            name="Telegram",
        ),
    ]
