# Generated by Django 2.1.7 on 2019-02-22 14:19

from django.db import migrations, models
from django.utils.crypto import get_random_string


def add_bm_id(apps, schema_editor):
    bk_object = apps.get_model("web", "Bookmarks")
    bookmarks = bk_object.objects.filter(bm_id=None)
    if bookmarks:
        for bookmark in bookmarks:
            bookmark.bm_id = get_random_string(7)
            bookmark.save()


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_auto_20190209_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="Bookmarks",
            name="bm_id",
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.RunPython(add_bm_id),
        migrations.AlterField(
            model_name="Bookmarks",
            name="bm_id",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
