# Generated by Django 2.1.7 on 2019-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_profile_scheduledtasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
