# Generated by Django 2.2.3 on 2019-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_auto_20190319_1944"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarks",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
