# Generated by Django 2.2.4 on 2019-08-11 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_bookmarks_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarkTags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=30)),
                (
                    "bookmark_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.Bookmarks"
                    ),
                ),
            ],
        ),
    ]
