# Generated by Django 2.2.4 on 2019-08-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_auto_20190812_0055"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmarktags",
            old_name="tag",
            new_name="name",
        ),
    ]
