# Generated by Django 2.2.4 on 2019-08-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20190812_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarktags',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
