# Generated by Django 2.2.8 on 2020-02-06 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0021_auto_20190819_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activation_code",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
