# Generated by Django 2.1.5 on 2019-02-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegram",
            name="activated",
            field=models.BooleanField(default=False),
        ),
    ]
