# Generated by Django 3.2.16 on 2023-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190210_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunSQL("INSERT INTO settings_site (allow_registration) VALUES (true);")
    ]
